service: project-golgi

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.8
  region: ap-southeast-1
  stage: dev
  timeout: 10
  memorySize: 128
  environment:
    THUMBNAIL_S3_BUCKET: ${self:custom.thumbnailRepository.bucket}
    THUMBNAIL_SIZE: 128
    REGION_NAME: ${self:provider.region}
  iam:
    role:
      statements:
        - Effect: 'Allow'
          Resource: arn:aws:s3:::${self:custom.uploads.bucket}/*
          Action: 's3:GetObject'
        - Effect: 'Allow'
          Resource: arn:aws:s3:::project-golgi-thumbnails/*
          Action: 's3:PutObject'

custom:
  uploads:
    bucket: project-golgi-uploads
  thumbnailRepository:
    bucket: project-golgi-thumbnails

functions:
  generate-thumbnail:
    handler: handler.generate_thumbnail
    events:
      - s3:
          bucket: ${self:custom.uploads.bucket}
          event: s3:ObjectCreated:*
          rules:
            - suffix: .png
          existing: true
    layers:
      - arn:aws:lambda:ap-southeast-1:770693421928:layer:Klayers-p38-Pillow:1
